Update on-demand-history-recovery-configuration.md
osisoft/PI-Adapter-OPC-UA-Docs pull request #77
Opened 2022-05-24 18:51 UTC by akiaei

timestamp update for WI https://dev.azure.com/osieng/engineering/_sprints/taskboard/Aurora/engineering/2022/Q2/2022.06.08?workitem=308001
Timestamps that don't specify UTC or local time get interpreted as local time of the adapter.
Ex:  "2022-05-23T11:00" will get interpreted as the same local time as the adapter ("2022-05-23T11:00-07:00") if the adapter is in PDT time (UTC -7:00)

2022-05-24 20:39 UTC, akiaei commented
I'm questioning if this is even needed anymore @zryska what do you think?
I feel like the documentation is clear enough that timestamps get interpreted into UTC

2022-05-25 06:39 UTC, zryska commented
> I'm questioning if this is even needed anymore @zryska what do you think? I feel like the documentation is clear enough that timestamps get interpreted into UTC

I agree and I would suggest rephrasing it to make sure we describe options and provide examples - to improve usability of the feature.

2022-05-25 18:46 UTC, rmuolic commented on content/main/shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> + **StartTime** | `datetime` | Time when the first data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends th
```suggestion
 **StartTime** | `datetime` | Time when the first data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends the following format for entering a startTime as UTC in a curl command: *YYYY-MM-DD*T*HH:MM:SS*Z. <br><br>**Note:** If a timestamp is not specified in UTC, the adapter assumes it is in local time and will interpret the timestamp to UTC. For example, a timestamp of "2022-05-23T11:00" will be interpreted as "2022-05-23T11:00-07:00" if the adapter is in PDT time (UTC -7:00).
```

2022-05-25 18:49 UTC, rmuolic commented on content/main/shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> + **EndTime** | `datetime`| Time when the last data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends the fo
```suggestion
 **EndTime** | `datetime`| Time when the last data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends the following format for entering a endTime as UTC in a curl command: *YYYY-MM-DD*T*HH:MM:SS*Z. <br><br>**Note:** If a timestamp is not specified in UTC, the adapter assumes it is in local time and will interpret the timestamp to UTC. For example, a timestamp of "2022-05-25T12:00" will be interpreted as "2022-05-25T12:00-07:00" if the adapter is in PDT time (UTC -7:00).
```

2022-05-25 18:50 UTC, rmuolic commented on content/main/shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> + **StartTime** | `datetime` | Time when the first data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends th
Added a suggested change @akiaei per our comments.

2022-05-25 18:50 UTC, rmuolic requested changes
Added suggested changes.

2022-05-26 12:47 UTC, aveva-jhwang reviewed
Zdenek shared this approval request with me. I think the wording is a little convoluted for what we want to convey to our customers. Could we update it to say something like this (formatting didn't carry over unfortunately)? 

---------------------
EndTime | datetime| Time when the last data items are collected.

Note: Timestamps are interpreted as Coordinated Universal Time (UTC) time standard.

To specify a timestamp in UTC standard, use the following format in a curl command: YYYY-MM-DDTHH:MM:SSZ.
To specify a timestamp in the local time of the PI Adapter, use the following format in a curl command: YYYY-MM-DDTHH:MM:SS.

2022-05-26 15:54 UTC, rmuolic commented on content/main/shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> + **StartTime** | `datetime` | Time when the first data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends th
```suggestion
 **StartTime** | `datetime` | Time when the first data items are collected.<br><br>**Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard.<br><br>To specify a timestamp in UTC standard, use the following format in a curl command: YYYY-MM-DDTHH:MM:SSZ.<br>To specify a timestamp in the local time of the PI Adapter, use the following format in a curl command: YYYY-MM-DDTHH:MM:SS.
```

2022-05-26 15:55 UTC, rmuolic commented on content/main/shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> + **EndTime** | `datetime`| Time when the last data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard. OSIsoft recommends the fo
```suggestion
 **EndTime** | `datetime`| Time when the last data items are collected.<br><br> **Note:** Timestamps are interpreted into the Coordinated Universal Time (UTC) time standard.<br><br>To specify a timestamp in UTC standard, use the following format in a curl command: YYYY-MM-DDTHH:MM:SSZ.<br>To specify a timestamp in the local time of the PI Adapter, use the following format in a curl command: YYYY-MM-DDTHH:MM:SS.
```

2022-05-26 15:58 UTC, rmuolic requested changes
Thank you @aveva-jhwang for your suggestion. It's a much cleaner approach w/o the need of a timestamp example. @akiaei please see my new suggestions to implement.

2022-05-26 17:14 UTC, rmuolic approved these changes

2022-05-26 17:19 UTC, AnnonsonTechWriter approved these changes

2022-05-26 17:34 UTC, zryska approved these changes

2022-05-26 18:06 UTC, aveva-jhwang approved these changes

2022-05-26 18:28 UTC, merged