Add documentation for serverFailoverEnable
osisoft/PI-Adapter-OPC-UA-Docs pull request #80
Opened 2022-07-26 19:44 UTC by bbilbrey-aveva

2022-07-26 19:52 UTC, derrick-at-aveva requested changes

2022-07-26 19:52 UTC, derrick-at-aveva commented on content/configuration/data-source.md
> +| **serverFailoverEnabled** | Optional | `boolean` | Specifies whether to use server-side failover. By default this is set to true and uses the server failover configuration. When set to false, the s
>Specifies whether to use server-side failover. By default this is set to true and uses the server failover configuration.

Those 2 sentences can be deleted without any loss of information.

2022-07-26 20:05 UTC, philliprlittle commented on content/configuration/data-source.md
> +| **serverFailoverEnabled** | Optional | `boolean` | Specifies whether to use server-side failover. By default this is set to true and uses the server failover configuration. When set to false, the s
I agree

2022-07-29 15:35 UTC, philliprlittle approved these changes
looks good

2022-07-29 15:41 UTC, derrick-at-aveva approved these changes

2022-07-29 15:42 UTC, rmuolic approved these changes

2022-08-03 19:27 UTC, bbilbrey-aveva commented
This feature has been removed.

2022-08-03 19:27 UTC, closed without merging